FROM golang:alpine  
WORKDIR /app
COPY main.go .
COPY pkg/ pkg/
COPY go.sum go.sum
COPY go.mod go.mod
RUN go mod download
RUN mkdir keys/
RUN go run pkg/auth/pem/main.go /app/keys terra-major-client
ENTRYPOINT go run main.go