version: "3.9"  # optional since v1.27.0
services:

  dev:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app

  release:
    build: .
    ports:
      - 80:80
    volumes:
      - ./:/app