version: "3.9"  # optional since v1.27.0
services:

  dev: &dev
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./pkg:/app/pkg
    environment:
      - PORT=8000

  characters:
    <<: *dev
    ports:
      - 8001:8001
    environment:
      - PKG=characters
      - PORT=8001

  instances:
    <<: *dev
    ports:
      - 8002:8002
    environment:
      - PKG=instances
      - PORT=8002

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - PORT=80

  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local