FROM golang:alpine  
WORKDIR /app
ENV GO111MODULE=on
# Need to install air within docker to work
RUN go install github.com/air-verse/air@latest 
COPY main.go .
COPY pkg/ pkg/
COPY go.sum go.sum
COPY go.mod go.mod
RUN go mod tidy
RUN go mod download
RUN mkdir keys/
RUN go run pkg/auth/pem/main.go /app/keys terra-major-client
ENTRYPOINT air