version: "3.9"  # optional since v1.27.0
services:

  dev:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - PORT=8000

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - PORT=80