version: "3.9" 

x-db-variables: &db-variables
  POSTGRES_HOST: postgres
  POSTGRES_USER: tmdbuser
  POSTGRES_PASSWORD: bigland
  POSTGRES_DATABASE: terramajor

networks:
  local:

services:

  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      <<: *db-variables
    hostname: postgres
    networks:
      local:
        aliases:
          - postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres:/var/lib/postgresql/data
      - ./pkg/core/sql:/docker-entrypoint-initdb.d

  dev: &dev
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    networks:
      local:
    volumes:
      - ./pkg:/app/pkg

  characters:
    <<: *dev
    ports:
      - 8001:8001
    environment:
      <<: *db-variables
      PKG: characters
      PORT: 8001

  instances:
    <<: *dev
    ports:
      - 8002:8002
    environment:
      <<: *db-variables
      PKG: instances
      PORT: 8002

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      PORT: 80

volumes:
  postgres:
    driver: local