version: "3.9" 

x-db-variables: &db-variables
  POSTGRES_HOST: $POSTGRES_HOST
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_DATABASE: $POSTGRES_DATABASE
  POSTGRES_SSL: $POSTGRES_SSL

networks:
  local:

services:

  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      <<: *db-variables
    hostname: postgres
    networks:
      local:
        aliases:
          - postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres:/var/lib/postgresql/data

  dev: 
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      <<: *db-variables
      PKG: characters
      PORT: 8000
    networks:
      local:
    ports:
      - 8000:8000
    volumes:
      - ./pkg:/app/pkg

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      <<: *db-variables
      PORT: 80
    networks:
      local:
    ports:
      - 80:80

volumes:
  postgres:
    driver: local