name: Trigger auto deployment for terra-major-instance-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/terra-major-instance-api-AutoDeployTrigger-7409c623-861c-41ff-bf81-b27f5b20f982.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: terramajor.azurecr.io
          username: ${{ secrets.TERRAMAJORINSTANCEAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.TERRAMAJORINSTANCEAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: terramajor.azurecr.io/terra-major-instance-api:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TERRAMAJORINSTANCEAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n terra-major-instance-api -g terra-major-non-prod --server terramajor.azurecr.io --username  ${{ secrets.TERRAMAJORINSTANCEAPI_REGISTRY_USERNAME }} --password ${{ secrets.TERRAMAJORINSTANCEAPI_REGISTRY_PASSWORD }}
            az containerapp update -n terra-major-instance-api -g terra-major-non-prod --image terramajor.azurecr.io/terra-major-instance-api:${{ github.sha }}
